# Generated by Django 2.0.4 on 2018-05-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codAsig', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('creditos', models.IntegerField(default=0)),
                ('nomAsig', models.CharField(max_length=40)),
                ('progAsig', models.CharField(max_length=6)),
                ('dia', models.CharField(max_length=10)),
                ('horas', models.CharField(max_length=5)),
                ('nomProf', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nomAsig',),
            },
        ),
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('nomCoord', models.CharField(max_length=40)),
                ('codCoord', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10)),
                ('anio', models.IntegerField(max_length=4)),
                ('codCoord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('ciProf', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nomProf', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nomUsr', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('claveUsr', models.CharField(max_length=16)),
                ('tipoUsr', models.CharField(choices=[('C', 'Coordinador'), ('E', 'Estudiante')], max_length=1)),
                ('codCoord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='ciProf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Profesor'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='codCoord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='ofertas',
            field=models.ManyToManyField(to='coordinaAsignaturas.Oferta'),
        ),
    ]
