# Generated by Django 2.0.4 on 2018-05-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='codCoord',
            new_name='nomCoord',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='codCoord',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='diaHora',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinador',
            name='nomCoord',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion'),
            preserve_default=False,
        ),
    ]
