# Generated by Django 2.0.4 on 2018-06-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinador',
            old_name='nomCoord',
            new_name='coordinacion',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='nomCoord',
            new_name='coordinacion',
        ),
    ]
