# Generated by Django 2.0.4 on 2018-05-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codAsig',
            field=models.CharField(default='NOEXIST', max_length=7),
        ),
    ]
