# Generated by Django 2.0.4 on 2018-06-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0002_auto_20180603_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacion',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, to='coordinaAsignaturas.Asignatura'),
        ),
    ]
