# Generated by Django 2.0.4 on 2018-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0003_auto_20180606_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='vista',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codDpto',
            field=models.CharField(blank=True, choices=[('EA', 'Estudios Ambientales'), ('CE', 'Ciencias Económicas y Administrativas'), ('CC', 'Ciencia y Tecnología del Comportamiento'), ('FIS', 'Física'), ('QM', 'Química'), ('MC', 'Mecánica'), ('MA', 'Matemáticas Puras y Aplicadas'), ('CI', 'Computación y Ciencias de la Información'), ('CO', 'Cómputo Científico y Estadística'), ('EC', 'Electrónica y Circuitos'), ('TF', 'Termodinámica y Fenómenos de Transferencia'), ('PS', 'Procesos y Sistemas'), ('MT', 'Ciencias de los Materiales'), ('GC', 'Ciencias de la Tierra'), ('LL', 'Lengua y Literatura'), ('ID', 'Idiomas'), ('FLX', 'Filosofía'), ('CS', 'Ciencias Sociales'), ('DA', 'Diseño Arquitectura y Artes Plásticas'), ('PL', 'Planificación Urbana'), ('BC', 'Biología Celular'), ('EA', 'Estudios Ambientales'), ('BO', 'Biología de Organismos'), ('PB', 'Tecnología de Procesos Biológicos y Bioquímicos')], max_length=6),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='diaHora',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nomAsig',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='progAsig',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
