# Generated by Django 2.0.4 on 2018-06-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0005_auto_20180628_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='coordinacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion'),
        ),
    ]
