# Generated by Django 2.0.4 on 2018-06-29 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0006_auto_20180628_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='progAsig',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1967), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='trimestre',
            field=models.CharField(choices=[('Ene-Mar', 'Enero-Marzo'), ('Abr-Jul', 'Abril-Julio'), ('Sept-Dic', 'Septiembre-Diciembre')], max_length=7),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1970)]),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='coordinacion',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta',
            name='trimestre',
            field=models.CharField(choices=[('Ene-Mar', 'Enero-Marzo'), ('Abr-Jul', 'Abril-Julio'), ('Sept-Dic', 'Septiembre-Diciembre')], max_length=7),
        ),
    ]
