# Generated by Django 2.0.4 on 2018-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0007_auto_20180629_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='trimestre',
            field=models.CharField(choices=[('Ene-Mar', 'Enero-Marzo'), ('Abr-Jul', 'Abril-Julio'), ('Sept-Dic', 'Septiembre-Diciembre')], max_length=8),
        ),
    ]
