# Generated by Django 2.0.5 on 2018-06-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0008_auto_20180629_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='coordinacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion'),
        ),
    ]
