# Generated by Django 2.0.5 on 2018-06-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaAsignaturas', '0009_auto_20180629_0502'),
        ('coordinaAsignaturas', '0009_auto_20180629_1145'),
    ]

    operations = [
    ]
